# Generated by Django 2.0.7 on 2019-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('POST_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TOPIC', models.CharField(max_length=30)),
                ('TEXT', models.TextField()),
            ],
        ),
    ]
