# Generated by Django 2.0.7 on 2019-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='DATE',
            field=models.DateField(auto_now=True),
        ),
    ]
