# Generated by Django 2.0.7 on 2019-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='DATE',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='TIME',
            field=models.TimeField(default=''),
        ),
    ]
