# Generated by Django 2.0.7 on 2019-06-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190626_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BLOG_NAME', models.CharField(max_length=20)),
                ('HOME_SUBTITLE', models.CharField(max_length=30)),
                ('ABOUT_SUBTITLE', models.CharField(max_length=30)),
                ('SELF_INTRODUCTION', models.TextField()),
                ('HOME_BG_IMG', models.ImageField(upload_to='')),
                ('ABOUT_BG_IMG', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='BACKGROUND_IMG',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='SUBTITLE',
            field=models.CharField(default='', max_length=30),
        ),
    ]
