# Generated by Django 2.0.7 on 2019-06-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190629_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_information',
            name='ABOUT_BG_IMG',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='blog_information',
            name='HOME_BG_IMG',
            field=models.CharField(max_length=30),
        ),
    ]
